### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [Divya-Manivannan1/PersonalPortfolio#9]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages)
2. A public GitHub repository for your codebase
3. Use HTML & SCSS
4. Make good use of semantic HTML elements
5. Be responsive (mobile-first) and built with accessibility in mind
6. Code is highly readable (good naming and indented correctly)

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Waiheke-Course-Resources/blob/main/student-resources/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 40 / 50  |
| Responsiveness       | 15 / 15  |
| Code Knowledge & Use | 15 / 20  |
| Readability          | 15 / 15  |
| Version Control      | 10 / 10  |
| Total Score          | 95 / 110 |

### Positive

- Your project is great! it has been a good exercise for you to build a website from a wireframe.
  - If you ever need a break pick a website and try and recreate it.
- I am glad you pushed yourself by choosing to break your styles into multiple logical files.
- Keep challenging yourself by doing additional research!
  - It is interesting to see mixins, functions and maps in SCSS. Great job!
- It is good that you have added your profile picture, Keep on adding to the portfolio as you complete projects and have your profile completed.
  - Keep your portfolio up to date!
- Great use of media queries, try using variables for the breakpoints in your next project.
  - `@media screen and (min-width: 768px) {}` -> `@media screen and (min-width: $get-breakpoint("tablet")) {}`
- You are demonstrating a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex.

### Constructive

- You have a slight side scroll on your page on the desktop, this is because you are using 100vw in places but also have padding on the body this can cause elements to overflow as it affects the overall dimensions of the document's layout.

  - I would remove the padding from the body and add padding to your structural tags.
  - Where you have 100vw try using 100% instead.
  - If this fails you can set the body to have overflow-x as hidden but this should be a last resort.

- You can simplify how you set up your grid, grid template columns are overkill for layouts like below. You have to assign each item a name.
  - If one item has to span across the grid just select the item and get it to do so, the grid layout will be able to do the rest.

```scss
.projects {
  // ...

  @media screen and (min-width: 768px) {
    &__card--tablet {
      display: grid;
      grid-template: 1fr 4fr 4fr/ 1fr 1fr 1fr;
      grid-template-areas:
        "subheading subheading subheading"
        "card1 card2 card3"
        "card4 card5 card6";

      &__subheading {
        grid-area: subheading;
        text-align: center;
      }

      &__card:nth-of-type(1) {
        grid-area: card1;
      }
      &__card:nth-of-type(2) {
        grid-area: card2;
      }
      &__card:nth-of-type(3) {
        grid-area: card3;
      }
      &__card:nth-of-type(4) {
        grid-area: card4;
      }
      &__card:nth-of-type(5) {
        grid-area: card5;
      }
      &__card:nth-of-type(6) {
        grid-area: card6;
      }
    }
  }
}

// COULD BE

.projects {
  // ...

  @media screen and (min-width: 768px) {
    &__card--tablet {
      display: grid;
      grid-template: 1fr 4fr 4fr/ 1fr 1fr 1fr;

      &__subheading {
        // GET THE HEADING TO START AT THE FIRST COLUMN NUMBER AND SPAN TO THE LAST NUMBER
        grid-column: 1 / -1;
        text-align: center;
      }
      // THE REST OF THE ITEMS WILL GET PLACED BY GRID
    }
  }
}
```

- The `<summary>` tag is used within `<details>` elements to provide a summary or caption for the details content.
  - The "About Me" section should be a semantic HTML element like the other section use a `<section>` instead.
  - [W3](https://www.w3schools.com/tags/tag_summary.asp)
- I think you should hide the burger menu on the desktop, it should only be visible when it is needed.
  - `<i class="header__menu--hidden fa-solid fa-bars"></i>` & `.header__menu--hidden { display : hidden }`

---
